doc-warnings: yes
test-warnings: yes
strictness: veryhigh
max-line-length: 80
autodetect: yes
requirements:
    - requirements.txt
    - test-requirements.txt
ignore-paths:
    - doc
    - seedbox/db/sqlalchemy/migrate_repo
