language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- 'pypy'
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
script:
- python setup.py flake8
- python setup.py testr --slowest --coverage --coverage-package-name='seedbox'
after_success: coveralls