language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
install:
  - pip install -q -r requirements.txt
  - pip install -q -r test-requirements.txt
  - python setup.py -q install
script:
  - flake8
  - python setup.py test --coverage --coverage-package-name='seedbox' 
after_success: coveralls
